[package]
name = "gihex-widget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = { version = "0.7.3" }


[[example]]
name = "gihex_gauge"
