name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt install libgtk-4-dev build-essential
    - name: Build Lib
      run: cargo build --verbose
    - name: Build Examples
      run: cargo build --examples
